riskler = {
    "alcohol denat": {"yağlı": "denge bozucu", "kuru": "kurutucu", "karma": "denge bozucu", "hassas": "bariyer zayıflatıcı"},
    "ethanol": {"kuru": "nem kaybı", "hassas": "tahriş riski"},
    "isopropyl alcohol": {"kuru": "nem kaybı", "hassas": "tahriş riski"},
    "fragrance": {"karma": "hassas bölgelerde risk", "hassas": "iritasyon riski", "kuru": "tahriş riski"},
    "parfum": {"karma": "hassas bölgelerde risk", "hassas": "iritasyon riski", "kuru": "tahriş riski"},
    "essential oils": {"karma": "reaksiyon riski", "hassas": "alerji riski"},
    "sodium lauryl sulfate": {"kuru": "bariyer bozucu", "hassas": "tahriş edici", "karma": "dengesizlik"},
    "ammonium lauryl sulfate": {"kuru": "kurutucu", "hassas": "tahriş edici"},
    "menthol": {"kuru": "kuruluk artırabilir", "karma": "iritasyon riski", "hassas": "tahriş edici"},
    "camphor": {"kuru": "kuruluk, hassasiyet", "hassas": "yanma hissi"},
    "isopropyl palmitate": {"yağlı": "komedojenik", "karma": "akneye meyilli alanlar"},
    "myristyl myristate": {"yağlı": "komedojenik"},
    "lauric acid": {"yağlı": "komedojenik"},
    "coconut oil": {"yağlı": "komedojenik", "karma": "T-bölgesi riski"},
    "cocos nucifera oil": {"yağlı": "komedojenik", "karma": "T-bölgesi riski"},
    "cocoa butter": {"yağlı": "komedojenik"},
    "wheat germ oil": {"yağlı": "yüksek komedojenite"},
    "algae extract": {"yağlı": "akneye yatkınlık"},
    "lanolin": {"yağlı": "tıkanma riski", "karma": "yağlı bölgelerde risk"},
    "acetylated lanolin": {"yağlı": "tıkanma riski", "karma": "yağlı bölgelerde risk"},
    "butyl stearate": {"yağlı": "yağlanma artışı"},
    "sodium chloride": {"yağlı": "bazı formüllerde irritan"},
    "mineral oil": {"yağlı": "ağır yapı", "karma": "ağır yapı"},
    "petrolatum": {"karma": "ağır yapı"},
    "shea butter": {"karma": "bazı bölgelerde ağır"},
    "silicone derivatives": {"karma": "oklüzif etki"},
    "hamamelis virginiana": {"kuru": "kurutucu olabilir", "karma": "kuru bölgeleri kurutabilir"},
    "witch hazel": {"kuru": "kurutucu olabilir", "karma": "kuru bölgeleri kurutabilir"},
    "benzoyl peroxide": {"kuru": "kuruluk artışı"},
    "retinol": {"kuru": "kuruluk yapabilir"},
    "salicylic acid": {"kuru": "yüksek oranda kurutucu"},
    "clay": {"kuru": "yağı fazla çeker"},
    "kaolin": {"kuru": "yağı fazla çeker"},
    "bentonite": {"kuru": "yağı fazla çeker"},
    "acetone": {"kuru": "aşırı kurutucu"},
    "lactic acid": {"kuru": "tahriş riski", "hassas": "tahriş riski"},
    "urea": {"kuru": "yüksek oranda irritan"},
    "limonene": {"hassas": "alerjen potansiyeli"},
    "linalool": {"hassas": "alerjen potansiyeli"},
    "eugenol": {"hassas": "alerjen potansiyeli"},
    "cinnamal": {"hassas": "alerjen"},
    "phenoxyethanol": {"hassas": "hassasiyet riski"},
    "methylisothiazolinone": {"hassas": "alerjik risk"},
    "benzalkonium chloride": {"hassas": "tahriş edici"},
    "benzyl alcohol": {"hassas": "kızarıklık riski"},
    "formaldehyde-releasing preservatives": {"hassas": "alerji riski"},
    "eucalyptus globulus oil": {"hassas": "yanma hissi"},
    "glycolic acid": {"hassas": "düşük pH irritasyonu"},
    "parabens": {"hassas": "bazı hassas ciltlerde reaksiyon", "kuru": "bazı hassasiyetler", "karma": "bazı hassasiyetler", "yağlı": "bazı hassasiyetler"},
    "isopropyl myristate": {"yağlı": "komedojenik"}

}
